### ISSUE TITLE
The game got stuck on fighting Sticky Hands

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#20] opened 2019-05-09 16:29 UTC
![image](https://user-images.githubusercontent.com/2095534/57470070-4b8a8a00-7288-11e9-9032-8ce5d760557d.png)

He refused to end his turn after inserting both dice into Run Away!. Possible consequence of Lock?'s extra dice affecting how the AI thinks?

**Comment by onetruepurple** [comment] 2019-05-09 16:31
Happened again after continuing. Definite case of Lock? interfering with the thought process
![image](https://user-images.githubusercontent.com/2095534/57470226-9e644180-7288-11e9-8d8d-cae6e069b703.png)

**Comment by onetruepurple** [comment] 2019-05-09 16:33
Update: lock?ing Marshmallow put a small delay on ending the turn, but the game continued

**Comment by onetruepurple** [comment] 2019-05-09 19:28
Crystalina was very confused by Counter? as well:

![image](https://user-images.githubusercontent.com/2095534/57480982-6b7a7780-72a1-11e9-8657-5d90e2957eb2.png)

**Comment by ncrecc** [comment] 2019-05-09 19:50
Dupe of #13 for the most part, some useful information in here though.

**Comment by TerryCavanagh** [comment] 2019-05-10 23:06
I think this is due to the old AI Lock? bug, closed here: https://github.com/TerryCavanagh/diceydungeonsbeta/issues/4! Should be fixed in the next build!

**Closed as completed by TerryCavanagh** 2019-05-10 23:06 UTC
Labels: v0.1: 9th May Build
