### ISSUE TITLE
In Warrior's first quest / tutorial, broadsword deals 10 damage with dice 6 instead of 8

### ISSUE THREAD

**Issue by musicalentropy** [TerryCavanagh/diceydungeonsbeta#393] opened 2019-07-25 13:08 UTC
It seems the amount of damage done to the enemies is right, but the one displayed in the piece of equipment during attack is wrong. I think that bug affects most of the player equipment supposed to deal damage with additional offsets.

**Comment by paceheart** [comment] 2019-08-04 00:09
Reproduced in RC3. It does the right amount of damage, but claims the wrong amount.
![Dicey Dungeons Aug 03 05-06-31PM broadsword adds 4 not 2](https://user-images.githubusercontent.com/38589027/62417934-69f6ec00-b611-11e9-9ca8-31207ab66e5e.png)

**Comment by ncrecc** [comment] 2019-08-10 16:18
Duplicate of #339

**Comment by TerryCavanagh** [comment] 2020-09-26 07:01
Fixed!

**Closed as completed by TerryCavanagh** 2020-09-26 07:01 UTC
Labels: release candidate v0.1
