### ISSUE TITLE
Enemy AI softlocks under Handyman rule in Bonus Round

### ISSUE THREAD

**Issue by paceheart** [TerryCavanagh/diceydungeonsbeta#457] opened 2019-07-31 06:13 UTC
![Dicey Dungeons Jul 31 01-07-28AM Sorceress can't handle Inventor rule](https://user-images.githubusercontent.com/38589027/62187670-bc918900-b32f-11e9-8141-98a82489b53e.png)

I shocked Sorceress, and she needs to put an even dice to unshock Cauldron, but she put her only even dice into Electric Shock, and tried to put a 1 into unshocking Cauldron. It didn't work, but she stubbornly refuses to acknowledge that it didn't work. Softlock!

I'm able to save and quit, then replay the fight, but I bet this won't be the last time I have to scum a fight to avoid this softlock.

**Comment by onetruepurple** [comment] 2019-07-31 10:09
Duplicate of #416

**Comment by TerryCavanagh** [comment] 2020-08-29 09:09
Fixed!

**Closed as completed by TerryCavanagh** 2020-08-29 09:09 UTC
Labels: release candidate v0.1, High Priority
