### ISSUE TITLE
UI shakes on overworld if you use spooky fury on boomerang and you get hit twice on the levelup screen

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#724] opened 2019-10-25 21:00 UTC
![wra](https://user-images.githubusercontent.com/11216597/67604194-f284b480-f748-11e9-805d-2b17727c703d.gif)

**Comment by ncrecc** [comment] 2019-10-26 17:11
Maybe this also happens with regular fury (when stacked)?

**Comment by TerryCavanagh** [comment] 2019-10-27 21:08
This happens very occasionally if you win a fight with Boomerang. It's been around for a little while! There's a duplicate of it somewhere in the main issues tracker - probably not gonna get it fixed for Halloween!

**Closed as completed by TerryCavanagh** 2019-10-27 21:08 UTC
Labels: Halloween Special
