### ISSUE TITLE
'This'll be fine' episode: curse status doesn't increment if already cursed

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#391] opened 2019-07-25 11:47 UTC
![gif](https://giant.gfycat.com/EarlyMintyAmericanwirehair.gif)
HD: https://gfycat.com/earlymintyamericanwirehair
Despite what the status bar indicates, it appears you have two curses in this situation:

In the gif:
1. Kraken cursed me
2. At start of my turn, curse status showed only one curse
3. I used an item and curse triggered
4. The curse status didn't clear, leading me to suspect that (as per the episode rules) I actually had two curses. I defeated the enemy before I could find out unfortunately.

**Comment by ncrecc** [comment] 2019-07-27 03:40
Dupe of https://github.com/TerryCavanagh/diceydungeons.com/issues/1141

**Comment by TerryCavanagh** [comment] 2019-08-11 22:02
Fixed!

**Closed as completed by TerryCavanagh** 2019-08-11 22:02 UTC
Labels: release candidate v0.1, High Priority
