### ISSUE TITLE
[rc5] Crash involving Challenges and Backstage

### ISSUE THREAD

**Issue by sstangl** [TerryCavanagh/diceydungeonsbeta#681] opened 2019-08-12 01:01 UTC
This crash reliably reproduces. Unfortunately no stack trace is given (Null Object Reference).

To reproduce:

1. Unlock everything in the editor.
2. On the title screen, click "Play".
3. Click on the Lady Luck head to switch to Backstage.
4. Click the "Challenges" button.
5. Click the "Back" button. It now has Backstage selected, but the graphics aren't showing the back stage door -- they're showing the stage. The text is "Backstage / ??? / Difficulty (5 stars)".
6. Click on any dice character, like the Jester. The game crashes.

**Comment by mrcdk** [comment] 2019-08-12 09:05
Duplicate of #646 Fixed.

**Closed as completed** 2019-08-12 10:37 UTC
