### ISSUE TITLE
Traded Plasma Blaster for Juggling Ball, kept both

### ISSUE THREAD

**Issue by paceheart** [TerryCavanagh/diceydungeonsbeta#582] opened 2019-08-04 19:07 UTC
This was my loadout:

![Dicey Dungeons Aug 04 12-05-27PM free trade](https://user-images.githubusercontent.com/38589027/62427987-52bb0b80-b6b0-11e9-92d0-ed5e2f98731f.png)

I traded Plasma Blaster for Juggling Ball, then realized I still had my Plasma Blaster.

Perhaps it's because the equipment was different sizes, and the Juggling Ball didn't fit into my equipped equipment?

**Comment by ncrecc** [comment] 2019-08-05 03:49
Duplicate of https://github.com/TerryCavanagh/diceydungeons.com/issues/569

**Closed as completed** 2020-09-26 08:30 UTC
Labels: release candidate v0.3
