### ISSUE TITLE
Thief steals Lock 1 from Copycat, but Copycat doesn't have Lock 1 (or in fact, any equipment)

### ISSUE THREAD

**Issue by paceheart** [TerryCavanagh/diceydungeonsbeta#452] opened 2019-07-30 04:02 UTC
Thief Bonus Round, Warlock and Hothead rules.

![copycat copies your equipment](https://user-images.githubusercontent.com/38589027/62099756-b5e21380-b254-11e9-9d68-0af32813d36c.png)

I had fought Keymaster in the immediately preceding fight. Here's what Enemy Preview looks like.
![copycat preview](https://user-images.githubusercontent.com/38589027/62099824-e75adf00-b254-11e9-803c-f9f79e0e61e9.png)

**Comment by paceheart** [comment] 2019-07-30 04:06
Copycat put a 1 in Plaster (?), a 3 in Wrecking Ball, then a 2 in Wrecking Ball. Then the equipment just sat there at zero for about 3 seconds, then the turn ended as usual. I was quick enough to snap a screenshot:
![Copycat hung here for about 3 seconds](https://user-images.githubusercontent.com/38589027/62099935-53d5de00-b255-11e9-822c-b73c744cdf2d.png)

**Comment by TerryCavanagh** [comment] 2020-09-26 07:27
Oh, this is a duplicate of another issue I just transfered. I think it might even be fixed now, though I'm not 100% sure!

**Closed as completed by TerryCavanagh** 2020-09-26 07:27 UTC
Labels: release candidate v0.1
