### ISSUE TITLE
"to do: using finders keepers in the editor with new level up screen"

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#222] opened 2019-06-23 21:32 UTC
![](https://cdn.discordapp.com/attachments/591227440144318464/592186092586008618/unknown.png)
How old is this error? "New level up screen" makes me suspect at least 0.16.

**Comment by ncrecc** [comment] 2019-08-03 22:14
Similar todo error with completing a battle as Inventor and going to the gadget screen

**Comment by TerryCavanagh** [comment] 2020-09-26 03:22
There's a duplicate of this on the main repo <3

**Closed as completed by TerryCavanagh** 2020-09-26 03:22 UTC
Labels: v0.5: 21st June Build
