### ISSUE TITLE
[1.0] When a Jester card is hit by Curse, no card is drawn to take its place

### ISSUE THREAD

**Issue by sstangl** [TerryCavanagh/diceydungeonsbeta#708] opened 2019-08-14 21:51 UTC
![Screenshot from 2019-08-14 15-34-53](https://user-images.githubusercontent.com/171223/63058957-58340500-beab-11e9-80c0-09ddd6ba165b.png)

**Comment by ncrecc** [comment] 2019-08-16 20:25
Duplicate of #136

**Comment by ncrecc** [comment] 2020-06-26 18:15
This has been fixed.

**Closed as completed** 2020-06-27 03:29 UTC
Labels: release candidate v0.5
