### ISSUE TITLE
Plus on damage being doubled

### ISSUE THREAD

**Issue by Classified9999** [TerryCavanagh/diceydungeonsbeta#651] opened 2019-08-10 14:10 UTC
When putting dice into equipment with [] + x, when it showed the total number, it showed it as if x was twice its actual value.

**Comment by ncrecc** [comment] 2019-08-10 16:18
Duplicate of #339

**Comment by TerryCavanagh** [comment] 2019-08-12 14:25
Fixed!

**Closed as completed by TerryCavanagh** 2019-08-12 14:25 UTC
Labels: High Priority, release candidate v0.5
