### ISSUE TITLE
[rc5] If you continuously click right arrow on the character select screen, things go a bit nuts

### ISSUE THREAD

**Issue by sstangl** [TerryCavanagh/diceydungeonsbeta#682] opened 2019-08-12 01:07 UTC
Normally on the character select screen if you click on a dice portrait, the current dice zooms out, and a new dice zooms in.

If you keep clicking on the right arrow, the new characters that appear suddenly start off as the same size as your screen. The faster you click, the larger they start as. If you click fast enough, they can grow larger than your screen, and the screen becomes saturated by a single color.

**Comment by mrcdk** [comment] 2019-08-12 09:07
Duplicate of #639 Fixed

**Closed as completed** 2019-08-12 10:37 UTC
