### ISSUE TITLE
AI gets bricked when using countdown cards?

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#13] opened 2019-05-09 16:07 UTC
![](https://i.frogbox.es/lob)
Poison Slingshot was shocked?, Super Dryad unshocked? it, put a 3 in it, then just gave up. It's still sitting there. I have no idea what caused this.

**Comment by ncrecc** [comment] 2019-05-09 16:14
Seems like shock? doesn't matter here:

[12:01 PM] codyfun123:
![](https://cdn.discordapp.com/attachments/552131784939405332/576076199613300772/unknown.png)
[12:01 PM] codyfun123: he's not doing anything
...
[12:13 PM] ncrecc: \@codyfun123 when haunted jar got bricked, was it after it unshocked something?
[12:13 PM] codyfun123: no
[12:13 PM] codyfun123: i didn't have shock that run

Might have to do with counter?/lock?, or maybe just countdowns in general.

**Comment by ncrecc** [comment] 2019-05-10 21:28
![](https://i.frogbox.es/lof)
Apparently this doesn't have anything to do with countdowns. Frog is stuck here after unshocking small shield.

**Comment by TerryCavanagh** [comment] 2019-05-10 23:05
I believe this is a duplicate of https://github.com/TerryCavanagh/diceydungeonsbeta/issues/4 (all these screenshots have either Lock or Counter X active!). If you spot this anywhere else, though, please let me know!

**Closed as completed by TerryCavanagh** 2019-05-10 23:05 UTC
Labels: v0.1: 9th May Build
